spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_AWS_ENDPOINT}/rgt?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER_NAME}
    password: ${DB_SECRET}


